const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
const datos={vencimientos:[],faltantes:[],resumen:{},unidades:[{id:1,patente:'TEST001',sucursal:'CAT'}],personas:[],tipos:[{id:1,nombre:'VTV',ambito:'unidad',aviso_dias:30,meses:12}]};
let report={id:'00112233-4455-4677-8899-aabbccddeeff',unidad_id:1,patente:'TEST001',chofer:'Ana',estado:'PENDIENTE',urgencia:'PUEDE_ESPERAR',descripcion:'Pierde aire',ocurrido_en:new Date().toISOString(),fotos:0};
await page.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.pathname==='/api/yo')return route.fulfill({json:{nombre:'Admin',puede_administrar:true}});
if(url.pathname==='/api/vencimientos'){if(req.method()==='GET')return route.fulfill({json:datos});requests.push(req.postDataJSON());return route.fulfill({json:{ok:true}});}
if(url.pathname==='/api/reportes-chofer'){if(req.method()==='POST'){const d=req.postDataJSON();requests.push(d);if(d.op==='desestimar'){if(!d.motivo.trim())return route.fulfill({status:400,json:{error:'Indicá el motivo.'}});report={...report,estado:'DESESTIMADA',motivo:d.motivo};}else report={...report,estado:'ORDEN_CREADA',orden_id:42,orden_numero:99};return route.fulfill({json:{ok:true,orden_id:report.orden_id}});}return route.fulfill({json:url.searchParams.get('op')==='contexto'?{gestiona:true}:[report]});}
const rel=url.pathname==='/vencimientos'?'vencimientos.html':url.pathname==='/fallas'?'choferes/bandeja.html':url.pathname.slice(1);const f=path.join(root,rel);if(fs.existsSync(f)&&fs.statSync(f).isFile())return route.fulfill({path:f});return route.fulfill({body:'',contentType:'text/javascript'});});
await page.goto('http://taller.test/vencimientos');await page.click('#configVenc');await page.fill('#cfgMeses','18');await page.fill('#cfgDias','45');await page.click('#cfgGuardar');await page.waitForFunction(()=>!document.querySelector('#modalConfigVenc').classList.contains('on'));assert(requests.some(r=>r.op==='configurar_tipo'&&r.meses==='18'&&r.aviso_dias==='45'));
await page.click('#nuevo');await page.selectOption('#cUnidad','1');await page.fill('#cVence','2027-02-28');await page.fill('#cAviso','2027-01-31');await page.click('#guardar');await page.waitForFunction(()=>!document.querySelector('#modalCarga').classList.contains('on'));assert(requests.some(r=>r.op==='guardar'&&r.aviso_fecha==='2027-01-31'));
await page.goto('http://taller.test/fallas');await page.getByRole('button',{name:'Desestimar solicitud'}).click();await page.getByText('Indicá el motivo.',{exact:true}).waitFor();await page.locator('textarea').fill('Duplicada');await page.getByRole('button',{name:'Desestimar solicitud'}).click();await page.selectOption('#filter','DESESTIMADA');await page.getByText('Motivo: Duplicada').waitFor();
report={...report,estado:'PENDIENTE',motivo:null};await page.selectOption('#filter','PENDIENTE');await page.click('#refresh');await page.locator('input[type=number]').fill('120000');await page.getByRole('button',{name:'Crear orden de trabajo'}).click();await page.selectOption('#filter','ORDEN_CREADA');await page.getByRole('link',{name:'Abrir OT 99'}).waitFor();assert.equal(await page.getByRole('link',{name:'Abrir OT 99'}).getAttribute('href'),'/ordenes?orden=42');
await page.screenshot({path:'/tmp/fallas-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: configuration, explicit dates, reason required, dismissal, OT link, desktop/mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
