// Run with Playwright installed. BROWSER_PATH optionally selects a local Chrome.
const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=[],enabled=true,fail=false,rol='admin';
const tickets=Array.from({length:61},(_,i)=>({id:i,remito:String(1000+i),fecha:'2026-09-08',patente:'AB123CD',litros:100+i,importe:150000,estacion:'Estación Norte',chofer:'Chofer de prueba'}));
const total={mes:'2026-09-01',litros:7930,importe:9150000,km:30000,litros_100km:26.4,cargas:61,unidades:1};
await page.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.pathname==='/api/yo')return route.fulfill({json:{nombre:'Usuario de prueba',rol}});
if(url.pathname==='/api/asistente'){if(req.method()==='GET')return route.fulfill({json:{habilitado:enabled}});requests.push(req.postDataJSON());return route.fulfill(fail?{status:503,json:{error:'Fuente no disponible'}}:{json:{respuesta:'Hay 70 cubiertas en stock. <img src=x onerror=alert(1)>',fuentes:[{fuente:'Gomería',url:'/gomeria',consultado:'2026-09-08T12:00:00-03:00',resumen:{cantidad:70},filtros:{dominio:'cubiertas',estado:'stock'},truncado:true}]}});}
if(url.pathname==='/api/combustible'){if(req.method()==='POST'){const body=req.postDataJSON();requests.push(body);return route.fulfill({json:body.confirmar?{nuevas:1,leidas:1,guardadas:1}:{previo:true,leidas:1,descartadas:0,repetidos:[],cabeceras:['remito','fecha','patente','litros','importe','estacion'],usadas:{remito:'remito',fecha:'fecha',patente:'patente',litros:'litros',importe:'importe'},muestra:[tickets[0]]}});}if(url.searchParams.get('vista')==='flota')return route.fulfill({json:{mes:'2026-09-01',total,meses:[total],unidades:[{...total,patente:'AB123CD'}]}});return route.fulfill({json:{tickets,resumen:[{estado:'ok',remitos:1}],cruce:[{remito:'1000',fecha:'2026-09-08',patente:'AB123CD',estado:'ok',litros_planilla:100,litros_estacion:100,dif_litros:0,dif_importe:0}],lotes:[]}});}
if(url.pathname==='/logo.png')return route.fulfill({body:fs.readFileSync(path.join(__dirname,'..','logo_diemar4.png')),contentType:'image/png'});
const file={'/combustible':'combustible.html','/asistente':'asistente.html'}[url.pathname];if(file)return route.fulfill({body:fs.readFileSync(path.join(__dirname,'..',file),'utf8'),contentType:'text/html'});return route.abort();});
await page.goto('http://taller.test/combustible');await page.locator('#ticket-rows tr').first().waitFor();assert.equal(await page.locator('#ticket-rows tr').count(),50);await page.click('#next-page');assert.equal(await page.locator('#ticket-rows tr').count(),11);await page.fill('#ticket-search','1001');assert.equal(await page.locator('#ticket-rows tr').count(),1);await page.click('#clear-filters');await page.click('[data-view="cruce"]');await page.locator('#cross-view').waitFor({state:'visible'});await page.click('[data-view="resumen"]');await page.locator('#totales .tarjeta').first().waitFor();assert.equal(await page.locator('#totales .tarjeta').count(),6);assert.equal(await page.locator('#g-meses svg').count(),1);await page.screenshot({path:'/tmp/fuel-summary.png'});
await page.click('[data-view="tickets"]');await page.locator('#tickets-view').waitFor({state:'visible'});await page.click('#new-ticket');for(const [name,value] of Object.entries({remito:'300',fecha:'2026-09-08',patente:'AB123CD',litros:'100.25',importe:'150000.50',estacion:'Norte'}))await page.fill(`[name="${name}"]`,value);await page.click('#ticket-form button[type=submit]');await page.locator('#p-planilla .guardar').waitFor();assert.equal(requests.at(-1).confirmar,false);const csv=Buffer.from(requests.at(-1).contenido,'base64').toString();assert(csv.includes('100.25'));await page.click('#p-planilla .guardar');await page.waitForFunction(()=>document.querySelector('#p-planilla').textContent.includes('Guardado'));assert.equal(requests.at(-1).confirmar,true);
await page.setViewportSize({width:390,height:844});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'fuel mobile overflow');rol='operario';await page.reload();await page.locator('#quien').getByText('operario',{exact:false}).waitFor();assert(!await page.locator('#new-ticket').isVisible());assert(!await page.locator('#imports').isVisible());rol='admin';
await page.goto('http://taller.test/asistente');await page.waitForFunction(()=>!document.querySelector('#send').disabled);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'chat mobile overflow');await page.fill('#question','¿Cuántas gomas hay?');await page.click('#send');await page.locator('.message.assistant').waitFor();assert.equal(await page.locator('.answer img').count(),0);assert.equal(await page.locator('.sources a').getAttribute('href'),'/gomeria');await page.fill('#question','¿Y montadas?');await page.click('#send');await page.waitForFunction(()=>document.querySelectorAll('.message.assistant').length===2);assert.equal(requests.at(-1).mensajes.length,3);fail=true;await page.fill('#question','otra');await page.click('#send');await page.locator('#error').waitFor({state:'visible'});assert.equal(await page.inputValue('#question'),'otra');await page.click('#reset');assert.equal(await page.locator('.message').count(),0);enabled=false;await page.reload();await page.locator('#error').waitFor({state:'visible'});assert(await page.locator('#send').isDisabled());enabled=true;await page.setViewportSize({width:1440,height:1000});await page.reload();await page.waitForFunction(()=>!document.querySelector('#send').disabled);await page.screenshot({path:'/tmp/chat-internal.png'});assert.deepEqual(errors,[]);console.log('PASS: fuel table/search/pagination/summary/import preview+save/read-only/mobile; chat follow-up, XSS, sources, retry, reset, missing key and mobile.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
